### ISSUE TITLE
Error al ejecutar: npm run build

### ISSUE THREAD

**Issue by jab3** [jerosoler/newpct-total#1]
Buenas noches! vaya pintaza tiene esto!

pues me da error al intentar instalarlo, no se si es por ansias o porque fallara algo de mi maquina:

`root@Torrents:~/newpct-total# npm run build

> newpct-total@1.0.0 build /root/newpct-total
> nuxt build && backpack build

/root/newpct-total/node_modules/nuxt/lib/core/module.js:14
  async ready() {
        ^^^^^

SyntaxError: Unexpected identifier
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/root/newpct-total/node_modules/nuxt/lib/core/index.js:2:16)

npm ERR! Linux 4.13.13-5-pve
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "build"
npm ERR! node v6.11.4
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! newpct-total@1.0.0 build: `nuxt build && backpack build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the newpct-total@1.0.0 build script 'nuxt build && backpack build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the newpct-total package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     nuxt build && backpack build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs newpct-total
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls newpct-total
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/newpct-total/npm-debug.log
root@Torrents:~/newpct-total#

gracias y saludos!`

**Comment by jerosoler** [comment]
Hola @jab3 

Es por la versión de node que utilizas que es vieja (6.11.4). El metodo async / await fue implementado a partir de la versión 7. Instala la 8 que es la recomendada o la 9. 
Para sistemas debian ubuntu: https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions

Saludos

**Comment by jab3** [comment]
Gracias!  En cuanto llegue a casa pruebo

**Comment by jab3** [comment]
Solucionado! mil gracias!

Esto es una maravilla!! cubre todas mis necesidades... aunque yo lo del streaming no le voy a dar uso xD (en principio)

Lo que si me pasa es el royo de que vodafone tiene capado a newpct.com.

He ido a modificar los datos que me dijiste en el otro programa en el build/main.js y en principio "funciona" al menos añade los torrents... pero a la hora de cargar las imágenes en el index o al buscar algo se carga toda la estética y salen imágenes grandes o hay espacios en blanco raros... quizás para  mi problema no creo que sea tan sencillo como sustituir las lineas que me comentaste no ?

Saludos!

**Comment by jerosoler** [comment]
Para quitar el bloqueo de Vodafone puedes probar con la ip directamente de newpct.

No se si la cambiaran mucho o el servidor tendra una ipfija. 
Pero con el comando: 
```
nslookup www.newpct.com 8.8.8.8
```
Ahora mismo: 
185.118.55.86

```bash
nslookup www.newpct.com 8.8.8.8
Server:         8.8.8.8
Address:        8.8.8.8#53

Non-authoritative answer:
Name:   www.newpct.com
Address: 185.118.55.86
```

Si entras a la url, carga newpct: http://185.118.55.86/
Otra seria utilizar una url con un proxy pero no se si serviria: 
http://anonymouse.org/cgi-bin/anon-www.cgi/http://www.newpct.com


Para modificar no tendrias que modificar el build/main, tendrias que modificar las carpetas:  server (Creo que esta todo aquí lo que enlaza a newpct), pages... 

Y luego ejecutar nuevamente el npm run build, que generara el archivo modificado. 

Espero que te sirva alguna de ellas. 

Saludos, Jero

**Comment by jab3** [comment]
Porfin lo he solucionado!!!!

despues de hacer mil pruebas con ips dns proxyes.... siempre intentando cambiar todas las lineas donde aparecia www.newpct.com , al final la solucion fue tan simple como añadir el proxy que me diste aqui:

 `exec('transmission-remote -a http://anonymouse.org/cgi-bin/anon-www_de.cgi/' + urltorrent, function (error, stdout, stderr) {`

asi que ahora perfecto!! esperemos que no me de mucho castigo jajaja

muchas gracias!

**Comment by jerosoler** [comment]
Perfecto! ;) 

Recuerda que esta linea esta en los dos archivos: 
/server/api/newpctauto.js  (Autodescargas)
/server/api/newpct.js (Descargas de pagina)

Saludos! ;)
