### ISSUE TITLE
Error al enviar descarga a transmission

### ISSUE THREAD

**Issue by txolo99** [jerosoler/newpct-total#10]
Al darle click a cualquier peli/serie para descargar a través de transmission no hace nada y salta este error en los logs:

0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node',
1 verbose cli   '/usr/lib/node_modules/pm2/lib/ProcessContainerFork.js',
1 verbose cli   'start' ]
2 info using npm@6.4.1
3 info using node@v8.15.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle newpct-total@1.0.0~prestart: newpct-total@1.0.0
6 info lifecycle newpct-total@1.0.0~start: newpct-total@1.0.0
7 verbose lifecycle newpct-total@1.0.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle newpct-total@1.0.0~start: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/root/newpct-total/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/root
9 verbose lifecycle newpct-total@1.0.0~start: CWD: /root/newpct-total
10 silly lifecycle newpct-total@1.0.0~start: Args: [ '-c', 'cross-env NODE_ENV=production node build/main.js' ]
11 silly lifecycle newpct-total@1.0.0~start: Returned: code: 1  signal: null
12 info lifecycle newpct-total@1.0.0~start: Failed to exec start script
13 verbose stack Error: newpct-total@1.0.0 start: `cross-env NODE_ENV=production node build/main.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:915:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid newpct-total@1.0.0
15 verbose cwd /root/newpct-total
16 verbose Linux 4.15.17-1-pve
17 verbose argv "/usr/bin/node" "/usr/lib/node_modules/pm2/lib/ProcessContainerFork.js" "start"
18 verbose node v8.15.0
19 verbose npm  v6.4.1
20 error code ELIFECYCLE
21 error errno 1
22 error newpct-total@1.0.0 start: `cross-env NODE_ENV=production node build/main.js`
22 error Exit status 1
23 error Failed at the newpct-total@1.0.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by jerosoler** [comment]
Hola @txolovinsky 
Tienes actualizado el programa? 
Que url tienes en Configuración -> Configurar otra URL -> Url de busqueda:
Pon esta: http://pctnew.com

Saludos

**Comment by txolovinsky** [comment]
Sí lo tengo actualizado a la última y efectivamente tenía puesto en url de búsqueda "descargas2020". Parece que con pctnew chuta
