### ISSUE TITLE
Solo envía las películas y no las series 

### ISSUE THREAD

**Issue by Znationpx** [jerosoler/newpct-total#11]
Hola desde hace unos días solo envía a transmission los torrent de las películas automáticamente en cambio las series me notifica que las encuentra por Telegram pero no las manda automáticamente a bajar ,si las pongo yo manual si se ponen,me podrías ayudar ,gracias y gran trabajo

**Comment by jerosoler** [comment]
Hola @Znationpx 

Que busqueda utilizas? 
Utilizas http://pctnew.com/ ?

Si es así
Has hecho el último cambio publicado? --->  https://github.com/jerosoler/newpct-total/commit/515ea1f806d867835afff55b5b5adc3e33cd4dff

Saludos

**Comment by Znationpx** [comment]
Hola @jerosoler 
Si utilizó esa búsqueda pero no entiendo que hay que hacer con ese cambio ,me podrías decir los pasos ? Gracias !

**Comment by jerosoler** [comment]
Hola, tienes que hacer:
Los siguientes comandos en la carpeta del programa:
`git pull`
Y después
`npm run build`
y después ejecutar-lo de nuevo. 

Si no haz un backup y descarga-lo de nuevo. 
O substituye esto en:
  nombre = nombre.replace("Calidad", " Calidad ");
Por
    nombre = nombre.replace("Calidad ", " Calidad de la Serie ");
En el archivo server/api/newpctautosearch.js


Saludos

**Comment by Znationpx** [comment]
@jwrosoler he cambiado esa línea pero sigue igual voy a tener que borrar y reinstalar de nuevo no ?

**Comment by jerosoler** [comment]
Una vez cambiada esa linea has hecho el build??

**Comment by Znationpx** [comment]
Lo acabo de hacer ha encontrado una serie peor me pasa lo mismo ,no sé pone en transmission

**Comment by jerosoler** [comment]
Puede ser que haya cambiado la pagina.

Y que haya que retocar el código.
Esperamos un par de días a ver...

**Comment by Znationpx** [comment]
E borrado y reinstalado a ver si ahora va ,si no a esperar toca ,gracias por tu ayuda y paciencia

**Comment by jerosoler** [comment]
Hola @Znationpx 
Hoy me ha descargado series sin problemas. 
Saludos

**Comment by Znationpx** [comment]
Edito @jerosoler reinstalando todo se ha solucionado sin problema gracias !!

**Comment by jerosoler** [comment]
@Znationpx  Perfecto!! ;)
