### ISSUE TITLE
Como funciona la opcion de Configuración Series/Pelis ?

### ISSUE THREAD

**Issue by jab3** [jerosoler/newpct-total#2]
Estoy intentando añadir mis series, y lo estare haciendo mal, ya que me agrega un poco de todo xD

En el newpct-auto editaba el archivo busqueda.js y añadia dentro de array una serie con este formato:
` ["Counterpart","AC3","Castellano"],`
y me iba perfecto.

Actualmente lo tengo de esta manera:

`Titulo: Counterpart       |      Filtros: AC3 Castellano`

Como seria la manera correcta?

gracias!

**Comment by jerosoler** [comment]
Hola,

Muy simple. El titulo es el nombre de la serie o peli para que tu lo sepas.
Y luego tienes que añadir los tags como hacías con el array. (Tienes que poner los tags separados. Si le das al intro te permite introducir más tags)

Aqui también he mejorado algo es que aun que lo escribas en mayúsculas lo buscara siempre en minúsculas.

Saludos, Jero

**Comment by jab3** [comment]
![recorte](https://user-images.githubusercontent.com/6956067/36122042-4a714562-1048-11e8-94c6-76713975742d.PNG)

asi es como lo tengo... y me ha añadido una pelicula llamada Teresa (WTF) y por eso me vino la duda

**Comment by jerosoler** [comment]
Tambien tienes que añadir blacklist a los filtros. Es decir:

Titulo: blacklist
Filtros: blacklist, ac3, castellano

Ahora como lo tienes te añadiría todo lo que lleve ac3 y castellano

**Comment by jab3** [comment]
Vaaale!! ahora te entendi !! perfecto! pues quizas lo deberias poner en el readme para que no le pase a la peña igual que ami jajaja

muchas gracias! un saludo!

**Comment by jerosoler** [comment]
Perfect!!

Lo tendre en cuenta y incluso en el mismo programa. En próximas actualizaciones.
