### ISSUE TITLE
Configurar dirección transmission

### ISSUE THREAD

**Issue by TraNk** [jerosoler/newpct-total#4]
Hola,

Me explico, tengo el transmission en un container, y tengo el newpct-total en otro. Mi idea es poder mandar los torrents al container del transmission. 

Esto es posible? o mejor que lo unifique? 

Gracias de antemano! y por tu trabajo :)

**Comment by jerosoler** [comment]
Hola
Basicamente lo que hace cuando se añade un torrent es lanzar el comando a la consola:
`exec('transmission-remote -a ' ...`

Mirando el help de transmission-remote tiene la posibilidad de ejecutar en otro host y port.
```
Usage: transmission-remote [host] [options]
       transmission-remote [port] [options]
       transmission-remote [host:port] [options]
       transmission-remote [http(s?)://host:port/transmission/] [options]
```

Si no otra opción seria, dependiendo de tus containers, si permiten enviar comandos entre maquinas:
`exec('comando_a_otra_maquina transmission-remote -a ' ...`

Los ficheros que tendrias que modificar son: 

- server/api/newpct.js
- server/api/newpctauto.js

Una vez modificado los comandos ejecturar de nuevo 
`npm run build` 
Y lanzar el servidor

Ya nos comentas si te sirve! ;) O la solución que has encontrado. 

Saludos

**Comment by jerosoler** [comment]
Por cierto actualmente esta habiendo problemas con el dominio de newpct, tendrias que hacer las modificaciones:
https://github.com/jerosoler/newpct-total/issues/3

**Comment by TraNk** [comment]
Hola! 

Probaré eso que dices a ver si lo consigo!

Y las modificaciones de los dominios ya los he cambiado! Gracias!

Saludos

**Comment by jerosoler** [comment]
Perfecto! Ya nos cuentas! ;)

**Comment by TraNk** [comment]
Muchas gracias!

Lo conseguí, he modificado los dos archivos que has comentado añadiendo estas lineas para que se conecte al otro container con este comando:

`transmission-remote [host:port] [options]`

Ejemplo:

`exec('transmission-remote 192.168.1.180:4100 -a' + urltorrent, function (error, stdout, stderr) {`

y

`exec('transmission-remote 192.168.1.180:4100 -n \''+response.user+':'+response.pass+'\' -a ' + urltorrent, func$`

He hecho un npm run build y luego npm start

Muchas gracias por la ayuda! :)

**Comment by jerosoler** [comment]
De nada! 

:)
