### ISSUE TITLE
Añadir notificacion por telegram?

### ISSUE THREAD

**Issue by jab3** [jerosoler/newpct-total#5]
Buenas jefe!

En mi servidor de descargas, hay varias personas que descargamos torrents desde aqui.... y si no miro cada dos por tres... pierdo el control.

Se me ha ocurrido, seria posible que cada vez que añadieran un torrent, te mandaran una notificacion via telegram ? por ejemplo: Añadido a descargas: titulo de la pelicula o torrent o lo que sea mas facil xD

Gracias y saludos!

**Comment by jerosoler** [comment]
Hola, @jab3 

Sencillo! ;) 

Modifica el archivo server/api/newpct.js

Añade de la función: 
```javascript
function telegram(message) {
  if(JSON.parse(fs.readFileSync('./db.json', 'utf8')).telegram.active){
    request('https://api.telegram.org/bot'+JSON.parse(fs.readFileSync('./db.json', 'utf8')).telegram.api+'/sendMessage?chat_id='+JSON.parse(fs.readFileSync('./db.json', 'utf8')).telegram.user+'&text='+message+'', function (error, response, body) {
      if(error){
        console.log('error:', error)
      }
    });
  }
}
```

Y luego en las lineas:
`res.json({ okey: 'Añadido', error: 'NO' });`

Añade a continuación lo siguiente: 
```javascript
telegram("Descargando: " + urltorrent);
```

Y de nuevo  `npm run build` ...

Espero que te sirva. 

Saludos, Jero

**Comment by jab3** [comment]
Sencillo para ti... que el que la lleva, la entiende jajaja aunque haciendo mis pruebas, no iba mal encaminado.... por curiosidad si en el texto pones una Ñ no funciona.

Que saliera el nombre seria mas complicado no?

Funciona a la perfeccion

Gracias y saludos!

**Comment by jerosoler** [comment]
Perfecto! ;) 

Seguramente es un caracter especial. Tendria que mirar de corregir.
