### ISSUE TITLE
Fallo al añadir capitulos de algunas series

### ISSUE THREAD

**Issue by jab3** [jerosoler/newpct-total#6]
He probado a añadir capitulos de la serie "scandals" no recientes... y este es el resultado

`LLamado: http://descargas2020.com/descargar-seriehd/scandal/capitulo-72/hdtv-720p-ac3-5-1/
Error: Can't set headers after they are sent.
    at validateHeader (_http_outgoing.js:494:11)
    at ServerResponse.setHeader (_http_outgoing.js:501:3)
    at ServerResponse.header (/root/newpct-total/node_modules/express/lib/response.js:767:10)
    at ServerResponse.send (/root/newpct-total/node_modules/express/lib/response.js:170:12)
    at ServerResponse.json (/root/newpct-total/node_modules/express/lib/response.js:267:15)
    at /root/newpct-total/build/webpack:/server/api/newpct.js:106:21
    at ChildProcess.exithandler (child_process.js:282:5)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
ReferenceError: location is not defined
    at VueComponent.created (layouts/default.b9423d943ec1d8ca5f15.js:135:102)
    at callHook (/root/newpct-total/node_modules/vue/dist/vue.runtime.common.js:2893:21)
    at VueComponent.Vue._init (/root/newpct-total/node_modules/vue/dist/vue.runtime.common.js:4558:5)
    at new VueComponent (/root/newpct-total/node_modules/vue/dist/vue.runtime.common.js:4726:12)
    at createComponentInstanceForVnode (/root/newpct-total/node_modules/vue-server-renderer/build.js:7166:10)
    at renderComponentInner (/root/newpct-total/node_modules/vue-server-renderer/build.js:7351:40)
    at renderComponent (/root/newpct-total/node_modules/vue-server-renderer/build.js:7326:5)
    at RenderContext.renderNode (/root/newpct-total/node_modules/vue-server-renderer/build.js:7242:5)
    at RenderContext.next (/root/newpct-total/node_modules/vue-server-renderer/build.js:2382:14)
    at cachedWrite (/root/newpct-total/node_modules/vue-server-renderer/build.js:2242:9)
    at renderElement (/root/newpct-total/node_modules/vue-server-renderer/build.js:7463:5)
    at renderNode (/root/newpct-total/node_modules/vue-server-renderer/build.js:7244:5)
    at renderComponentInner (/root/newpct-total/node_modules/vue-server-renderer/build.js:7362:3)
    at renderComponent (/root/newpct-total/node_modules/vue-server-renderer/build.js:7326:5)
    at RenderContext.renderNode (/root/newpct-total/node_modules/vue-server-renderer/build.js:7242:5)
    at RenderContext.next (/root/newpct-total/node_modules/vue-server-renderer/build.js:2382:14)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! newpct-total@1.0.0 start: `cross-env NODE_ENV=production node build/main.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the newpct-total@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-03-02T19_49_13_152Z-debug.log
`

saludos!

**Comment by jerosoler** [comment]
Uhhhhh!!! 

Si entras a la pagina veras que el torrent no existe:
http://descargas2020.com/descargar-seriehd/scandal/capitulo-72/hdtv-720p-ac3-5-1/

Aún que acabo de probar y veo que el programa devuelve el error. También se reinicia. Pero es por que no encuentra el torrent. 

Me lo apunto de corregir.

**Comment by jab3** [comment]
pues vaya mojon de web! no me habia percatado xD

en el otro dominio si que existe.... esta gente van de mal en peor xD

ya no sabe uno si apuntar a descargas2020 o tvsinpagar

**Comment by cmos486** [comment]
me uno para que se trabaje con http://tumejortorrent.com/ :P aunque no tiene feed ;(

**Comment by jerosoler** [comment]
Es lo que iva a comentar se aceptan peticiones! 

Tu mejor torrent si que tiene feed aún que muestra un error.
Aún que si miramos el view-source del feed quiza si que funcione, se tendria que testear.
view-source:http://tumejortorrent.com/feed

Igualmente se puede coger el feed de una y las busquedas de otra.

**Comment by jerosoler** [comment]
Teseado el feed lee hasta 240 items
news0: 21 Thunder - Temporada 1 [HDTV 720p][Cap.101_108][AC3 5.1 EspaÃ±ol Castellano]

news1: Alibi com Agencia De Engaños [BluRay Rip][AC3 2.0 Español Castellano][2018]

news2: Alibi com Agencia De Engaños [BluRay 720p X264 MKV][AC3 5.1 Castellano-Frances - Sub ES][2018]

news3: 21 Thunder - Temporada 1 [HDTV][Cap.101_108][EspaÃ±ol Castellano]

news4: Asesinato en el Orient Express [BDremux 1080p][DTS 5.1 Castellano-DTS-HD 5.1 Ingles+Subs][ES-EN]

news5: Tres Anuncios en las afueras [4K Remux][2160p][HDR][DTS 5.1-AC3 5.1 Castellano DTS 5.1-Ingles+Subs][ES-EN]

news6: Tres Anuncios en las afueras [MicroHD 1080p][AC3 5.1-DTS 5.1-Castellano-AC3 5.1 Ingles+Subs][ES-EN]

news7: Tres Anuncios en las afueras [BluRay 1080p][DTS 5.1 AC3 5.1 Castellano DTS 5.1-Ingles+Subs][ES-EN]

news8: Tres Anuncios en las afueras [BDremux 1080p][DTS 5.1 Castellano-DTS-HD 5.1 Ingles+Subs][ES-EN]

news9: Mal Genio [BluRay Rip][AC3 2.0 Español Castellano][2018]

news10: Mal Genio [BluRay 720p X264 MKV][AC3 5.1 Castellano-Frances - Sub ES][2018]

news11: Waco - Temporada 1 [HDTV 720p][Cap.105][V.O. Subt. Castellano]

news12: The Looming Tower - Temporada 1 [HDTV 720p][Cap.101_103][V.O. Subt. Castellano]

news13: The Flash - Temporada 4 [HDTV 720p][Cap.414][V.O. Subt. Castellano]

news14: The Blacklist - Temporada 5 [HDTV 720p][Cap.514][V.O. Subt. Castellano]

news15: iZombie - Temporada 4 [HDTV 720p][Cap.401][V.O. Subt. Castellano]

news16: Homeland - Temporada 7 [HDTV 720p][Cap.703][V.O. Subt. Castellano]

news17: Designated Survivor - Temporada 2 [HDTV 720p][Cap.211][V.O. Subt. Castellano]

news18: DCs Legends Of Tomorrow - Temporada 3 [HDTV 720p][Cap.312][V.O. Subt. Castellano]

news19: American Crime Story The Assassination of Gianni Versace - Temporada 2 [HDTV 720p][Cap.206][V.O. Subt. Castellano]

news20: The Magicians - Temporada 3 [HDTV][Cap.302][Español Castellano]

news21: The Magicians - Temporada 3 [HDTV 720p][Cap.302][AC3 5.1 Español Castellano]

news22: The Magicians - Temporada 3 [HDTV][Cap.301][Español Castellano]

news23: The Magicians - Temporada 3 [HDTV 720p][Cap.301][AC3 5.1 Español Castellano]

news24: Gone - Temporada 1 [HDTV][Cap.110][Español Castellano]

news25: Gone - Temporada 1 [HDTV 720p][Cap.110][AC3 5.1 Español Castellano]

news26: Einstein - Temporada 2 [HDTV][Cap.202][Español Castellano]

news27: Einstein - Temporada 2 [HDTV 720p][Cap.202][AC3 5.1 Español Castellano]

news28: 9-1-1  - Temporada 1 [HDTV][Cap.106][Español Castellano]

news29: 9-1-1  - Temporada 1 [HDTV 720p][Cap.106][AC3 5.1 Español Castellano]

news30: Gone - Temporada 1 [HDTV][Cap.109][Español Castellano]

news31: Gone - Temporada 1 [HDTV 720p][Cap.109][AC3 5.1 Español Castellano]

news32: La Vida En Piezas - Temporada 3 [HDTV 720p][Cap.307][AC3 5.1 Español Castellano]

news33: The Detour (Desviados) - Temporada 3 [HDTV][Cap.303][Español Castellano]

news34: The Detour (Desviados) - Temporada 3 [HDTV 720p][Cap.303][AC3 5.1 Español Castellano]

news35: Mi Madre Contra Todos [BluRay 720p X264 MKV][AC3 5.1 Castellano-Ingles - Sub ES][2018]

news36: El Instante Mas Oscuro [BluRay Rip][AC3 2.0 Español Latino][2018]

news37: Shot Caller [BluRay 720p X264 MKV][AC3 5.1 Castellano-Ingles - Sub ES][2018]

news38: Shot Caller [BluRayRIP][AC3 5.1 EspaÃ±ol Castellano][2018]

news39: Covert Affairs - Temporada 5 [HDTV 720p][Cap.515_516][AC3 5.1 EspaÃ±ol Castellano]

news40: Covert Affairs - Temporada 5 [HDTV][Cap.515_516][EspaÃ±ol Castellano]

news41: Mi Madre Contra Todos [BluRayRIP][AC3 5.1 EspaÃ±ol Castellano][2018]

news42: Asesinato en el Orient Express [4K Remux][2160p][HDR][AC3 5.1 Castellano TrueHD 7.1-Ingles+Subs][ES-EN]

news43: Asesinato en el Orient Express [BluRay 1080p][AC3 5.1 Castellano DTS 5.1-Ingles+Subs][ES-EN]

news44: Asesinato en el Orient Express [MicroHD 1080p][AC3 5.1-Castellano-AC3 5.1-Ingles+Subs][ES-EN]

news45: Crazy Ex Girlfriend - Temporada 3 [HDTV 720p][Cap.301_313][AC3 5.1 EspaÃ±ol Castellano]

news46: Crazy Ex Girlfriend - Temporada 3 [HDTV][Cap.301_313][EspaÃ±ol Castellano]

news47: Strike Back - Temporada 6 [HDTV 720p][Cap.608][AC3 5.1 EspaÃ±ol Castellano]

news48: Strike Back - Temporada 6 [HDTV][Cap.608][EspaÃ±ol Castellano]

news49: Channel Zero Butchers Block - Temporada 3 [HDTV 720p][Cap.304][AC3 5.1 EspaÃ±ol Castellano]

news50: Channel Zero Butchers Block - Temporada 3 [HDTV][Cap.304][EspaÃ±ol Castellano]

news51: American Assassin [4K Remux][2160p][HDR][AC3 5.1 Castellano TrueHD 7.1-Ingles+Subs][ES-EN]

news52: American Assassin [BluRay 1080p][AC3 5.1 Castellano DTS 5.1-Ingles+Subs][ES-EN]

news53: Tres Anuncios En Las Afueras [BluRay 720p X264 MKV][AC3 5.1 Castellano-Ingles - Sub ES][2018]

news54: American Assassin [MicroHD 1080p][AC3 5.1-Castellano-AC3 5.1-Ingles+Subs][ES-EN]

news55: Tres Anuncios En Las Afueras [BluRay Rip][AC3 5.1 Español Castellano][2018]

news56: Same Kind Of Different As Me [BluRay Rip][AC3 2.0 Español Latino][2018]

news57: Papeles En El viento [BluRay Rip][AC3 2.0 Español Latino][2018]

news58: Ferdinand [BluRay Rip][AC3 2.0 Español Latino][2018]

news59: Asesinato En El Orient Express [BluRay Rip][AC3 5.1 Español Castellano][2018]

news60: Asesinato en el Orient Express [BluRay 720p X264 MKV][AC3 5.1 Castellano-Ingles - Sub ES][2018]

news61: Sin Palabras - Temporada 2 [HDTV][Cap.205][Español Castellano]

news62: Sin Palabras - Temporada 2 [HDTV 720p][Cap.205][AC3 5.1 Español Castellano]

news63: Scandal - Temporada 7 [HDTV][Cap.711][Español Castellano]

news64: Scandal - Temporada 7 [HDTV 720p][Cap.711][AC3 5.1 Español Castellano]

news65: La Tregua  - Temporada 1 [HDTV][Cap.105][Español Castellano]

news66: La Tregua  - Temporada 1 [HDTV 720p][Cap.105][AC3 5.1 Español Castellano]

news67: Mentes Criminales - Temporada 13 [HDTV][Cap.1314][Español Castellano]

news68: Mentes Criminales - Temporada 13 [HDTV 720p][Cap.1314][AC3 5.1 Español Castellano]

news69: Homeland - Temporada 7 [HDTV][Cap.702][Español Castellano]

news70: Homeland - Temporada 7 [HDTV 720p][Cap.702][AC3 5.1 Español Castellano]

news71: Gomorra  - Temporada 3 [HDTV][Cap.310][Español Castellano]

news72: Gomorra  - Temporada 3 [HDTV 720p][Cap.310][AC3 5.1 Español Castellano]

news73: Gomorra  - Temporada 3 [HDTV][Cap.309][Español Castellano]

news74: Gomorra  - Temporada 3 [HDTV 720p][Cap.309][AC3 5.1 Español Castellano]

news75: Fariña  - Temporada 1 [HDTV][Cap.101][Español Castellano]

news76: Fariña  - Temporada 1 [HDTV 720p][Cap.101][AC3 5.1 Español Castellano]

news77: Anatomia De Grey - Temporada 14 [HDTV][Cap.1412][Español Castellano]

news78: Anatomia De Grey - Temporada 14 [HDTV 720p][Cap.1412][AC3 5.1 Español Castellano]

news79: Chicago PD - Temporada 5 [HDTV][Cap.508][Español Castellano]

news80: Chicago PD - Temporada 5 [HDTV 720p][Cap.508][AC3 5.1 Español Castellano]

news81: American Assassin [BluRay 720p X264 MKV][AC3 5.1 Castellano-Ingles - Sub ES][2018]

news82: American Assassin [BluRay Rip][AC3 5.1 EspaÃ±ol Castellano][2018]

news83: El Hijo De Bigfoot [BluRay Rip][AC3 2.0 EspaÃ±ol Latino][2018]

news84: Acapulo La Vida Va [BluRay Rip][AC3 2.0 EspaÃ±ol Latino][2018]

news85: Thor Ragnarok DTS [MicroHD 1080p][AC3 5.1-DTS 5.1-Castellano-AC3 5.1 Ingles+Subs][ES-EN]

news86: Thor Ragnarok DTS [BluRay 1080p][DTS 5.1-AC3 5.1 Castellano DTS 5.1-Ingles+Subs][ES-EN]

news87: Thor Ragnarok DTS [BDremux 1080p][DTS 5.1 Castellano-DTS 5.1 Ingles+Subs][ES-EN]

news88: Thor Ragnarok DTS [FullBluRay 1080p][Castellano DTS 5.1-Ingles DTS-HD 7.1+Subs][ES-EN]

news89: Z Nation - Temporada 4 [HDTV][Cap.409][Español Castellano]

news90: Z Nation - Temporada 4 [HDTV 720p][Cap.409][AC3 5.1 Español Castellano]

news91: Z Nation - Temporada 4 [HDTV][Cap.408][Español Castellano]

news92: Z Nation - Temporada 4 [HDTV 720p][Cap.408][AC3 5.1 Español Castellano]

news93: Younger - Temporada 4 [HDTV][Cap.412][Español Castellano]

news94: Younger - Temporada 4 [HDTV 720p][Cap.412][AC3 5.1 Español Castellano]

news95: Younger - Temporada 4 [HDTV][Cap.411][Español Castellano]

news96: Younger - Temporada 4 [HDTV 720p][Cap.411][AC3 5.1 Español Castellano]

news97: Scorpion - Temporada 4 [HDTV][Cap.416][Español Castellano]

news98: Scorpion - Temporada 4 [HDTV 720p][Cap.416][AC3 5.1 Español Castellano]

news99: Cuerpo de Elite  - Temporada 1 [HDTV][Cap.104][Español Castellano]

news100: Cuerpo de Elite  - Temporada 1 [HDTV 720p][Cap.104][AC3 5.1 Español Castellano]

news101: Cardinal  - Temporada 2 [HDTV][Cap.202][Español Castellano]

news102: Cardinal  - Temporada 2 [HDTV 720p][Cap.202][AC3 5.1 Español Castellano]

news103: Blue Bloods - Temporada 8 [HDTV][Cap.808][Español Castellano]

news104: Blue Bloods - Temporada 8 [HDTV 720p][Cap.808][AC3 5.1 Español Castellano]

news105: Nashville - Temporada 6 [HDTV 720p][Cap.606][AC3 5.1 Español Castellano]

news106: The Lovers [BluRay 720p X264 MKV][AC3 5.1 Castellano-Ingles - Sub ES][2018]

news107: Cardinal - Temporada 2 [HDTV][Cap.201][Español Castellano]

news108: The Lovers [BluRay Rip][AC3 5.1 EspaÃ±ol Castellano][2018]

news109: Nashville - Temporada 6 [HDTV][Cap.606][Español Castellano]

news110: Cardinal - Temporada 2 [HDTV 720p][Cap.201][AC3 5.1 Español Castellano]

news111: The Mick - Temporada 2 [HDTV][Cap.204][Español Castellano]

news112: The Mick - Temporada 2 [HDTV 720p][Cap.204][AC3 5.1 Español Castellano]

news113: La Forma Del Agua [BluRay Screneer][EspaÃ±ol Castellano][2018]

news114: Covert Affairs - Temporada 5 [HDTV 720p][Cap.510_514][AC3 5.1 EspaÃ±ol Castellano]

news115: Covert Affairs - Temporada 5 [HDTV][Cap.510_514][EspaÃ±ol Castellano]

news116: Perros de paja [BDremux 1080p][AC3 Castellano-AC3  Ingles+Subs][ES-EN]

news117: Bye Bye Germany [BluRay 720p X264 MKV][AC3 5.1 Castellano-Aleman - Sub ES][2018]

news118: Bye Bye Germany [BluRayRIP][AC3 5.1 EspaÃ±ol Castellano][2018]

news119: Amor A La Siciliana [BluRay 720p X264 MKV][AC3 5.1 Castellano-Italiano-Sub][2018]

news120: Amor A La Siciliana [BluRay Rip][AC3 5.1 Español Castellano][2018]

news121: The Crucifixion [MicroHD 1080p][AC3 5.1-Castellano-AC3 5.1-Ingles+Subs][ES-EN]

news122: The Crucifixion [BluRay 1080p][AC3 5.1 Castellano DTS 5.1-Ingles+Subs][ES-EN]

news123: The Last Man on Earth - Temporada 4 [HDTV][Cap.402][Español Castellano]

news124: The Last Man on Earth - Temporada 4 [HDTV][Cap.401][Español Castellano]

news125: The Last Man on Earth - Temporada 4 [HDTV 720p][Cap.402][AC3 5.1 Español Castellano]

news126: The Last Man on Earth - Temporada 4 [HDTV 720p][Cap.401][AC3 5.1 Español Castellano]

news127: The Crucifixion 3D [BluRay 1080p][AC3 5.1 Castellano DTS 5.1-Ingles+Subs][ES-EN]

news128: The Brave  - Temporada 1 [HDTV][Cap.106][Español Castellano]

news129: The Brave  - Temporada 1 [HDTV 720p][Cap.106][AC3 5.1 Español Castellano]

news130: SWAT  - Temporada 1 [HDTV][Cap.111][Español Castellano]

news131: SWAT  - Temporada 1 [HDTV 720p][Cap.111][AC3 5.1 Español Castellano]

news132: Oro  - Temporada 1 [HDTV][Cap.108][Español Castellano]

news133: Oro  - Temporada 1 [HDTV 720p][Cap.108][AC3 5.1 Español Castellano]

news134: Another Period  - Temporada 3 [HDTV][Cap.306][Español Castellano]

news135: Another Period  - Temporada 3 [HDTV 720p][Cap.306][AC3 5.1 Español Castellano]

news136: Another Period  - Temporada 3 [HDTV][Cap.305][Español Castellano]

news137: Another Period  - Temporada 3 [HDTV 720p][Cap.305][AC3 5.1 Español Castellano]

news138: The Crucifixion [Bluray Rip][AC3 5.1 Español Castellano][2018]

news139: The Crucifixion [BluRay 720p X264 MKV][AC3 5.1 Castellano-Ingles-Sub][2018]

news140: The Walking Dead - Temporada 8 [HDTV][Cap.809][Español Castellano]

news141: The Walking Dead - Temporada 8 [HDTV 720p][Cap.809][AC3 5.1 Español Castellano]

news142: Al Lado Del Enemigo [BluRay 720p X264 MKV][AC3 5.1 Castellano-Ingles-Sub][2018]

news143: Al Lado Del Enemigo [BluRay Rip][AC3 5.1 Español Castellano][2018]

news144: Cambio De Planes [BluRay 720p X264 MKV][AC3 5.1 Castellano-Ingles-Sub][2018]

news145: Cambio De Planes [BluRay Rip][AC3 5.1 Español Castellano][2018]

news146: Renegados [BluRay 720p X264 MKV][AC3 2.0 Castellano-Ingles-Sub][2018]

news147: Renegados [BluRay Rip][AC3 2.0 Español Castellano][2018]

news148: LA to Vegas - Temporada 1 [HDTV][Cap.105][Español Castellano]

news149: LA to Vegas - Temporada 1 [HDTV 720p][Cap.105][AC3 5.1 Español Castellano]

news150: Covert Affairs - Temporada 5 [HDTV 720p][Cap.505_509][AC3 5.1 Español Castellano]

news151: Covert Affairs - Temporada 5 [HDTV][Cap.505_509][Español Castellano]

news152: The Tunnel - Temporada 3 [HDTV][Cap.305][Español Castellano]

news153: The Tunnel - Temporada 3 [HDTV 720p][Cap.305][AC3 5.1 Español Castellano]

news154: Taken - Temporada 2 [HDTV][Cap.202][Español Castellano]

news155: Taken - Temporada 2 [HDTV 720p][Cap.202][AC3 5.1 Español Castellano]

news156: Crashing - Temporada 2 [HDTV][Cap.207][Español Castellano]

news157: Crashing - Temporada 2 [HDTV 720p][Cap.207][AC3 5.1 Español Castellano]

news158: Divorce - Temporada 2 [HDTV][Cap.207][Español Castellano]

news159: Divorce - Temporada 2 [HDTV 720p][Cap.207][AC3 5.1 Español Castellano]

news160: Here and Now - Temporada 1 [HDTV][Cap.103][Español Castellano]

news161: Here and Now - Temporada 1 [HDTV 720p][Cap.103][AC3 5.1 Español Castellano]

news162: The Walking Dead - Temporada 8 [HDTV 720p][Cap.809][V.O. Subt. Castellano]

news163: The Walking Dead - Temporada 8 [HDTV][Cap.809][V.O. Subt. Castellano]

news164: Counterpart - Temporada 1 [HDTV 720p][Cap.106][AC3 5.1 Español Castellano]

news165: Counterpart - Temporada 1 [HDTV][Cap.106][Español Castellano]

news166: Jungla [BDremux 1080p][DTS-HD 5.1 Castellano-DTS-HD 5.1 Ingles+Subs][ES-EN]

news167: Batman y Harley Quinn [4K Remux][2160p][HDR][AC3 5.1 Castellano DTS-MA 5.1-Ingles+Subs][ES-EN]

news168: Taken - Temporada 2 [HDTV][Cap.201][Español Castellano]

news169: Taken - Temporada 2 [HDTV 720p][Cap.201][AC3 5.1 Español Castellano]

news170: HitlerS Circle Of Evil - Temporada 1 [HDTV][Cap.101_110][Español Castellano]

news171: HitlerS Circle Of Evil - Temporada 1 [HDTV 720p][Cap.101_110][AC3 5.1 Español Castellano]

news172: Covert Affairs - Temporada 5 [HDTV][Cap.501_504][Español Castellano]

news173: Covert Affairs - Temporada 5 [HDTV 720p][Cap.501_504][AC3 5.1 Español Castellano]

news174: Novitiate [BluRay 720p X264 MKV][AC3 5.1 Castellano-Ingles-Sub][2018]

news175: Novitiate [BluRayRIP][AC3 5.1 Español Castellano][2018]

news176: The Blacklist - Temporada 5 [HDTV 720p][Cap.513][V.O. Subt. Castellano]

news177: Stargate Origins - Temporada 1 [HDTV 720p][Cap.102_105][V.O. Subt. Castellano]

news178: Homeland - Temporada 7 [HDTV 720p][Cap.702][V.O. Subt. Castellano]

news179: DCs Legends Of Tomorrow - Temporada 3 [HDTV 720p][Cap.311][V.O. Subt. Castellano]

news180: The Orville  - Temporada 1 [HDTV][Cap.112][Español Castellano]

news181: The Orville  - Temporada 1 [HDTV 720p][Cap.112][AC3 5.1 Español Castellano]

news182: Schitts Creek - Temporada 4 [HDTV][Cap.404][Español Castellano]

news183: Schitts Creek - Temporada 4 [HDTV 720p][Cap.404][AC3 5.1 Español Castellano]

news184: Ghosted - Temporada 1 [HDTV][Cap.106][Español Castellano]

news185: Ghosted - Temporada 1 [HDTV 720p][Cap.106][AC3 5.1 Español Castellano]

news186: Nuestra Vida En La Borgoña [BluRay Rip][AC3 5.1 Español Castellano][2018]

news187: Nuestra Vida En La Borgoña [BluRay 720p X264 MKV][AC3 5.1 Castellano-Frances-Sub][2018]

news188: Oro [BluRay 720p X264 MKV][AC3 2.0 Castellano][2018]

news189: Oro [BluRayRIP][AC3 2.0 Español Castellano][2018]

news190: Thor Ragnarok 3D [BluRay 1080p][AC3 5.1 Castellano DTS 5.1-Ingles+Subs][ES-EN]

news191: High Maintenance - Temporada 2 [HDTV][Cap.206][Español Castellano]

news192: High Maintenance - Temporada 2 [HDTV 720p][Cap.206][AC3 5.1 Español Castellano]

news193: DCs Legends Of Tomorrow - Temporada 3 [HDTV 720p][Cap.310][AC3 5.1 Español Castellano]

news194: DCs Legends Of Tomorrow - Temporada 3 [HDTV][Cap.310][Español Castellano]

news195: El Agente [BluRay Rip][AC3 2.0 Español Castellano][2018]

news196: El Agente [BluRay 720p X264 MKV][AC3 2.0 Castellano-Ingles-Sub][2018]

news197: Thor Ragnarok [4K Remux][2160p][HDR][AC3 5.1 Castellano TrueHD 7.1-Ingles+Subs][ES-EN]

news198: Thor Ragnarok [MicroHD 1080p][AC3 5.1-Castellano-AC3 5.1-Ingles+Subs][ES-EN]

news199: Thor Ragnarok [BluRay 1080p][AC3 5.1 Castellano DTS 5.1-Ingles+Subs][ES-EN]

news200: Thor Ragnarok [BDremux 1080p][AC3 5.1 Castellano-DTS 5.1 Ingles+Subs][ES-EN]

news201: Thor Ragnarok [BluRay Rip][AC3 5.1 Español Castellano][2018]

news202: Thor Ragnarok [BluRay 720p X264 MKV][AC3 5.1 Castellano-Ingles-Sub][2018]

news203: Jane The Virgin - Temporada 4 [HDTV][Cap.409][Español Castellano]

news204: Jane The Virgin - Temporada 4 [HDTV 720p][Cap.409][AC3 5.1 Español Castellano]

news205: Chicago Fire - Temporada 3 [HDTV 720p][Cap.322][AC3 5.1 Español Castellano]

news206: The Flash - Temporada 4 [HDTV 720p][Cap.411][AC3 5.1 Español Castellano]

news207: The Flash - Temporada 4 [HDTV][Cap.411][Español Castellano]

news208: Chicago Fire - Temporada 3 [HDTV][Cap.322][Español Castellano]

news209: Chicago Fire - Temporada 3 [HDTV][Cap.321][Español Castellano]

news210: Chicago Fire - Temporada 3 [HDTV 720p][Cap.321][AC3 5.1 Español Castellano]

news211: Mom - Temporada 5 [HDTV 720p][Cap.512][AC3 5.1 Español Castellano]

news212: Mom - Temporada 5 [HDTV][Cap.512][Español Castellano]

news213: 9-1-1 (Proper) - Temporada 1 [HDTV 720p][Cap.105][AC3 5.1 Español Castellano]

news214: 9-1-1 (Proper) - Temporada 1 [HDTV][Cap.105][Español Castellano]

news215: Seven Seconds - Temporada 1 [HDTV 720p][Cap.101_110][AC3 5.1 Español Castellano]

news216: Seven Seconds - Temporada 1 [HDTV][Cap.101_110][Español Castellano]

news217: The Tick - Temporada 1 [HDTV 720p][Cap.107_112][AC3 5.1 Español Castellano]

news218: El secreto de Marrowbone [FullBluRay 1080p][Castellano DTS-HD 5.1-Ingles DTS-HD 5.1+Subs][ES-EN]

news219: The Tick - Temporada 1 [HDTV][Cap.107_112][Español Castellano]

news220: El secreto de Marrowbone [BDremux 1080p][DTS-HD 5.1 Castellano-DTS-HD 5.1 Ingles+Subs][ES-EN]

news221: Marseille - Temporada 2 [HDTV][Cap.201_208][Español Castellano]

news222: Marseille - Temporada 2 [HDTV 720p][Cap.201_208][AC3 5.1 Español Castellano]

news223: Patti Cakes [BluRay Rip][AC3 5.1 Español Castellano][2018]

news224: Patti Cakes [BluRay 720p X264 MKV][AC3 5.1 Castellano-Ingles-Sub][2018]

news225: Mira Lo Que Has Hecho - Temporada 1 [HDTV][Cap.101_106][Español Castellano]

news226: Mira Lo Que Has Hecho - Temporada 1 [HDTV 720p][Cap.101_106][AC3 5.1 Español Castellano]

news227: Mudo [BluRay Rip][AC3 5.1 Español Castellano][2018]

news228: Mudo [BluRay 720p X264 MKV][AC3 5.1 Castellano][2018]

news229: This Is Us - Temporada 2 [HDTV][Cap.215][Español Castellano]

news230: This Is Us - Temporada 2 [HDTV 720p][Cap.215][AC3 5.1 Español Castellano]

news231: The Librarians - Temporada 4 [HDTV][Cap.412][Español Castellano]

news232: The Librarians - Temporada 4 [HDTV 720p][Cap.412][AC3 5.1 Español Castellano]

news233: The Librarians - Temporada 4 [HDTV][Cap.411][Español Castellano]

news234: The Librarians - Temporada 4 [HDTV 720p][Cap.411][AC3 5.1 Español Castellano]

news235: Navy Investigacion Criminal - Temporada 15 [HDTV][Cap.1514][Español Castellano]

news236: Navy Investigacion Criminal - Temporada 15 [HDTV 720p][Cap.1514][AC3 5.1 Español Castellano]

news237: Gone - Temporada 1 [HDTV][Cap.108][Español Castellano]

news238: Gone - Temporada 1 [HDTV 720p][Cap.108][AC3 5.1 Español Castellano]

news239: Einstein - Temporada 2 [HDTV][Cap.201][Español Castellano]

news240: Einstein - Temporada 2 [HDTV 720p][Cap.201][AC3 5.1 Español Castellano]

;)

**Comment by jab3** [comment]
Pues acabo de probar sustituir las descargas2020 por tumejortorrent salvo el feed... y parece que marcha bien

seguire testando 💃

**Comment by jab3** [comment]
Buenas!

Haciendo pruebas me pasó algo curioso.... como puse que las descarga las hiciera en tumejortorrent, fui a descargar la película los 4 fantásticos, y se reiniciaba el programa.... me fui a la web y ponía que el torrent no existía, miré en descargas2020 y tampoco existía, sin embargo mire en tvsinpagar y estaba perfecto.

Se me ha ocurrido, si seria posible meterle unos IF ....

Si esta el torrent en tumejortorrent , ok
sino, descargalo en descargas2020
y sino, descargalo en tvsinpagar

Serie un puntazo, ya que actualmente el cogido en lastres web funciona perfecto


Saludos!

**Comment by jerosoler** [comment]
Hola, @jab3 

Se podria llegar ha hacer. Lo que si cambia una url de una pagina a otra mierda...

Lo que estoy haiendo es otra cosa! Es que directamente desde el apartado de configuración se pueda cambiar el feed del cual coje los datos, pudiendo ademas escoger un url para la lista y otra para el feed. 

Lo estoy acabando en cuanto lo tenga te aviso! ;) 

Jero

**Comment by jerosoler** [comment]
Hola, @jab3 

Subido! 

## Cosas corregidas y añadidas:
- Listado de sitios
- Corregido copiar link de Streaming
- Añadido boton para descargar el Backup
- Corregido formulario de añadir nueva series
- Bugs menores


Para descargar el nuevo contenido, primero de todo hacer copia del archivo db.json ya que lo he tenido que modificar.

Entrar en el directorio de la aplicación: 
`git reset --hard HEAD`
Seguido de
`git pull origin master`

Las nuevas lineas añadidas al archivo json son: 
```json
,
  "urlsearch": {
    "url": "http://tumejortorrent.com/",
    "feed": "http://tumejortorrent.com/feed"
  }

```
Seguimos con los mismos pasos de siempre:
`npm run build`
y 
`npm run start o pm2... `

**Comment by jab3** [comment]
gracias! lo estoy probando... tvsinpagar no funciona, tambien he probado feed de tumejor torrent y busqueda de tvsinpagar, tampoco funciona

por otra parte .... se podria actualizar de otra manera alternativa a esta y no perder la configuracion ? o la modificacion que hice para que me notificara por telegram las descargas que se iniciaran desde la web?

**Comment by jerosoler** [comment]
Hola! 

La otra forma que hay de actualizar es a mano haciendo los cambios, aquí los últimos cambios:
https://github.com/jerosoler/newpct-total/commit/13f4c8342db48c46495c6856be101c5f38d589a1

A veces son pocos cambios y a veces muchos. Lo que lleva más trabajo. 

Quiza la otra opción seria añadir en el apartado de telegram otra opción para que notificara todas las descargas y así no tuvieras que hacerlo a mano.

**Comment by jab3** [comment]
asi es como empece a hacerlo, pero cuando vi tanto código nuevo.... dio pereza jajajaajaja

y viste lo de tvsinpagar ?

**Comment by jerosoler** [comment]
Si he visto que el feed de tvsinpagar no funciona. Y además veo que no actualizan el feed igual de rapido que la pagina. El feed supongo que lo generan con retraso.

He encontrado dos url's más:
http://torrentrapid.com/
http://torrentlocura.com/

Ahora estoy probando con torrentrapid que parece que funciona.

**Comment by jerosoler** [comment]
Ya no se utilizan feeds. Si no scrawler directp.
