### ISSUE TITLE
Se cierra el programa

### ISSUE THREAD

**Issue by avogabo** [jerosoler/newpct-total#7]
He conseguido instalarlo en un xpenology, pero a los pocos minutos de arrancar, se cierra solo y he de volver a arrancarlo

**Comment by jerosoler** [comment]
Si ejecutas npm start

Cuando se te cierra el programa que logs deja en la consola??

En caso de utilizar pm2. Utiliza el comando pm2 logs 0

**Comment by avogabo** [comment]
Vale, he consiguido que no cierre, ( llevo mas de 15 min con el corriendo en segundo plano) pero no puedo entrar en la configuracion,  network error 500

Enviado desde mi iPhone

El 18 oct 2018, a las 19:08, Jero Soler <notifications@github.com<mailto:notifications@github.com>> escribió:


Si ejecutas npm start

Cuando se te cierra el programa que logs deja en la consola??

En caso de utilizar pm2. Utiliza el comando pm2 logs 0

**Comment by jerosoler** [comment]
Te entra a ver el listado? 
Solo la pagina de configuracion?

Te ha dado problemas al ejecturar npm install??

**Comment by avogabo** [comment]
La pagina principal carga, ningun error durante la instalacion, solo cn la pagina de configuracion

Enviado desde mi iPhone

El 18 oct 2018, a las 19:46, Jero Soler <notifications@github.com<mailto:notifications@github.com>> escribió:


Te entra a ver el listado?
Solo la pagina de configuracion?

Te ha dado problemas al ejecturar npm install??

**Comment by jerosoler** [comment]
La consola no te muestra ningun error??

**Comment by jerosoler** [comment]
Estas intentando entrar por una ip o por un dominio? 

Me comentant que por dominio no entra. 
Has probado desde ip?

**Comment by avogabo** [comment]
Confirmado, desde red local con ip si funciona

Enviado desde mi iPhone

El 18 oct 2018, a las 20:24, Jero Soler <notifications@github.com<mailto:notifications@github.com>> escribió:


Prueba a modicar la pagina pages/config.vue y cambiar las llamadas por http://' + location.hostname + ' por tu direccion

Saludos

**Comment by avogabo** [comment]
Ok  siguiente... cada vez que intento descargar algo se cierra, he puesto mu user y pass de transmission y nada. Intento ver el log, pero me pide contraseña

Enviado desde mi iPhone

El 18 oct 2018, a las 20:24, Jero Soler <notifications@github.com<mailto:notifications@github.com>> escribió:


Prueba a modicar la pagina pages/config.vue y cambiar las llamadas por http://' + location.hostname + ' por tu direccion

Saludos

**Comment by jerosoler** [comment]
Prueba de cambiar a otra url de descarga desde la pagina de configuracion.

El log del processo no te tendria que pedir contraseña.

**Comment by avogabo** [comment]
Con tvsinpagarr no aparece ningún contenido,
Con tu mejor torrent, se cierra y no puedo abrir el log para verlo
Con torrentrapid da este error en consola al intentar descargar :

     npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! newpct-total@1.0.0 start: `cross-env NODE_ENV=production node build/main.js`
npm ERR! Exit status 1

Y con descargas2020 me da este error en la propia web:

      Error: Command failed: transmission-remote -n ‘mi user : mi pass' -a http://descargas2020.com/descargar-torrent/113178_-1539945936-daredevil---temporada-3--hdtv-720p-ac3-5-1/ /bin/sh: transmission-remote: command not found /bin/sh: transmission-remote: command not found


El 19 oct 2018, a las 7:37, Jero Soler <notifications@github.com<mailto:notifications@github.com>> escribió:


Prueba de cambiar a otra url de descarga desde la pagina de configuracion.

El log del processo no te tendria que pedir contraseña.

**Comment by jerosoler** [comment]
Tienes instalado Transmission? Mira que este instalado el paquete transmisson-remote

**Comment by avogabo** [comment]
Lo tengo instalado, el transmission remote creo que tb, porque creo que es el que usa tb sickrage//medusa

El 19 oct 2018, a las 19:04, Jero Soler <notifications@github.com<mailto:notifications@github.com>> escribió:


Tienes instalado Transmission? Mira que este instalado el paquete transmisson-remote

**Comment by jerosoler** [comment]
Si puedes acceder por consola prueba de ejecutar el comando:
` 
transmission-remote -V
`
Te tendria que devolver algo parecido a esto:
` 
transmission-remote 2.84 (14307)
`

O el mismos comando que te ha dado error: 
transmission-remote -n ‘mi user : mi pass' -a http://descargas2020.com/descargar-torrent/113178_-1539945936-daredevil---temporada-3--hdtv-720p-ac3-5-1/

**Comment by jerosoler** [comment]
Prueba a comprobar también si esta instalado que en el fichero /etc/transmission-daemon/settings.json
o donde lo guarde synologi. 
Este esto así: "rpc-whitelist-enabled": false,

**Comment by avogabo** [comment]
Command not found... ok debe ser eso, 
He buscado clmo instalaro pero solo veo con apt-get... y en synology no esta habilitado

Enviado desde mi iPhone

**Comment by avogabo** [comment]
Esta en false

Enviado desde mi iPhone

El 19 oct 2018, a las 19:31, Jero Soler <notifications@github.com<mailto:notifications@github.com>> escribió:


Prueba a comprobar también si esta instalado que en el fichero /etc/transmission-daemon/settings.json
o donde lo guarde synologi.
Este esto así: "rpc-whitelist-enabled": false,

**Comment by avogabo** [comment]
rpc-whitelist-enabled  en false

No se como puedo instalar transmission-remote

**Comment by avogabo** [comment]
Alguna otra idea?

Enviado desde mi iPhone

El 19 oct 2018, a las 19:31, Jero Soler <notifications@github.com<mailto:notifications@github.com>> escribió:


Prueba a comprobar también si esta instalado que en el fichero /etc/transmission-daemon/settings.json
o donde lo guarde synologi.
Este esto así: "rpc-whitelist-enabled": false,

**Comment by jerosoler** [comment]
Cerrado por inactividad
