### ISSUE TITLE
Problemas en la build

### ISSUE THREAD

**Issue by alienboyxp** [jerosoler/newpct-total#8]
Tengo este error al intentar ejecutar la build (npm run build) con la última version de Node.j sobre Mac OS Mojave... se te ocurre algo? 1000 Gracias!!!

> nuxt build && backpack build

node[28934]: ../src/node_file.cc:893:void node::fs::Stat(const FunctionCallbackInfo<v8::Value> &): Assertion `(argc) == (4)' failed.
 1: 0x1000623a3 node::Abort() [/usr/local/bin/node]
 2: 0x1000622d5 node::PrintErrorString(char const*, ...) [/usr/local/bin/node]
 3: 0x10006adbd node::fs::LStat(v8::FunctionCallbackInfo<v8::Value> const&) [/usr/local/bin/node]
 4: 0x1002292a7 v8::internal::FunctionCallbackArguments::Call(v8::internal::CallHandlerInfo*) [/usr/local/bin/node]
 5: 0x100228876 v8::internal::MaybeHandle<v8::internal::Object> v8::internal::(anonymous namespace)::HandleApiCallHelper<false>(v8::internal::Isolate*, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::FunctionTemplateInfo>, v8::internal::Handle<v8::internal::Object>, v8::internal::BuiltinArguments) [/usr/local/bin/node]
 6: 0x100227f70 v8::internal::Builtin_Impl_HandleApiCall(v8::internal::BuiltinArguments, v8::internal::Isolate*) [/usr/local/bin/node]
 7: 0xbf00bcfb7d 
sh: line 1: 28934 Abort trap: 6           nuxt build
npm ERR! code ELIFECYCLE
npm ERR! errno 134
npm ERR! newpct-total@1.0.0 build: `nuxt build && backpack build`
npm ERR! Exit status 134
npm ERR! 
npm ERR! Failed at the newpct-total@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /var/root/.npm/_logs/2018-11-20T15_12_26_340Z-debug.log

Y este el log de debug:
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'build' ]
2 info using npm@6.4.1
3 info using node@v11.2.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle newpct-total@1.0.0~prebuild: newpct-total@1.0.0
6 info lifecycle newpct-total@1.0.0~build: newpct-total@1.0.0
7 verbose lifecycle newpct-total@1.0.0~build: unsafe-perm in lifecycle true
8 verbose lifecycle newpct-total@1.0.0~build: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/juanjoser/Desktop/Torrent/newpct-total/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/A$
9 verbose lifecycle newpct-total@1.0.0~build: CWD: /Users/juanjoser/Desktop/Torrent/newpct-total
10 silly lifecycle newpct-total@1.0.0~build: Args: [ '-c', 'nuxt build && backpack build' ]
11 silly lifecycle newpct-total@1.0.0~build: Returned: code: 134  signal: null
12 info lifecycle newpct-total@1.0.0~build: Failed to exec build script
13 verbose stack Error: newpct-total@1.0.0 build: `nuxt build && backpack build`
13 verbose stack Exit status 134
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:182:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:182:13)
13 verbose stack     at maybeClose (internal/child_process.js:978:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)
14 verbose pkgid newpct-total@1.0.0
15 verbose cwd /Users/juanjoser/Desktop/Torrent/newpct-total
16 verbose Darwin 18.2.0
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build"
18 verbose node v11.2.0
19 verbose npm  v6.4.1
20 error code ELIFECYCLE
21 error errno 134
22 error newpct-total@1.0.0 build: `nuxt build && backpack build`
22 error Exit status 134
23 error Failed at the newpct-total@1.0.0 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 134, true ]

**Comment by jerosoler** [comment]
Prueba a borrar la carpeta node_modules y a borrar la cache de npm
`npm cache clean --force 
`

Y otra vez:
 install dependencies
`npm install # Or yarn install`
 Montando proyecto
`npm run build`
 Lanzando servidor
`npm start`

Si no prueba a ejecutar con
`npm run dev`
Haber si así funciona

Que versión de node tienes? 
`nodejs -v`

**Comment by alienboyxp** [comment]
Gracias por la rápida respuesta!!!
he ido avanzando y solventando problemas y ahora en npm run build me da este error
ERROR in ./.nuxt/client.js
Module build failed (from ./node_modules/eslint-loader/index.js):
TypeError: Cannot read property 'eslint' of undefined
    at Object.module.exports (/Users/juanjoser/Desktop/Torrent/newpct-total/node_modules/eslint-loader/index.js:148:18)
 @ multi ./.nuxt/client.js app[0]

 FATAL  Nuxt Build Error      
la version de js es la 10 LTS

**Comment by jerosoler** [comment]
Mira dentro de la carpeta node_modules si esta la carpeta "eslint-loader" y "eslint"
Si no instalalo.
`npm install eslint-loader eslint`

Prueba si no ha instalar todas las dependencias del package.json
```json 
 "devDependencies": {
    "babel-eslint": "^7.2.3",
    "backpack-core": "^0.4.1",
    "eslint": "^4.3.0",
    "eslint-config-standard": "^10.2.1",
    "eslint-loader": "^1.9.0",
    "eslint-plugin-html": "^3.1.1",
    "eslint-plugin-import": "^2.7.0",
    "eslint-plugin-node": "^5.1.1",
    "eslint-plugin-promise": "^3.5.0",
    "eslint-plugin-standard": "^3.0.1"
  }

```

**Comment by jerosoler** [comment]
Que versión de nodejs utilizas? 
`nodejs -v `

**Comment by alienboyxp** [comment]
node -v
v10.13.0

**Comment by jerosoler** [comment]
Hola, acabo de probar con una v10.13.0

Hazlo todo de nuevo pero en vez de hacer un npm install haz un npm update como te muestro abajo. 

```bash
#Download project
git clone https://github.com/jerosoler/newpct-total.git
# Entrar al directorio
cd newpct-total
# install dependencies
npm update
# Montando proyecto
npm run build
# Lanzando servidor
npm start # Or pm2 start npm --name="newpct" -- start
```

**Comment by alienboyxp** [comment]
Ahora siiii!!!
Muchisimas gracias!!! Si puedo hacerte unas preguntas/sugerencias :)
- hay posibilidad de que se pueda descargar el torrent a un directorio local que se pueda definir?
- hay posibilidad de que se pueda añadir 4K en los filtros?
- cada cuanto refresca la informacion de los diferentes proveedores?
- se puede automatizar el refresco de la informacion y que en base a filtros automaticamente descargue los torrents a un directorio o los envie por transmission?
Gracias!!! esta genial.

**Comment by jerosoler** [comment]
Hola, Perfecto que te funcione.

- hay posibilidad de que se pueda descargar el torrent a un directorio local que se pueda definir?
**Esta funcionalidad no la contemplo**
- se puede automatizar el refresco de la informacion y que en base a filtros automaticamente descargue los torrents a un directorio o los envie por transmission?
**Existe la opción de descargar automatica mediante filtros en el apartado config "Series/Pelis", te recomiendo poner descargas2020 que ahora funciona con ese. Se actualiza cada 10 minutos. Puedes ver como configurar-lo aquí: https://github.com/jerosoler/newpct-total/issues/2** 
- hay posibilidad de que se pueda añadir 4K en los filtros?...
**Me lo miro cuando pueda**

Saludos

**Comment by ibanana** [comment]
conseguido no me preguntes como pero listo gracias de todas formas
